package net.kigawa.kinfra.infrastructure.terraform

import net.kigawa.kinfra.infrastructure.config.ConfigRepository
import java.io.File

interface TerraformVarsManager {
    fun updateHostsVars()
    fun getVarsFilePath(): String
}

class TerraformVarsManagerImpl(
    private val configRepository: ConfigRepository,
    private val varsFilePath: String = "terraform/hosts.auto.tfvars"
) : TerraformVarsManager {

    override fun updateHostsVars() {
        val hostsConfig = configRepository.loadHostsConfig()
        val varsFile = File(varsFilePath)

        // 親ディレクトリが存在しない場合は作成
        varsFile.parentFile?.mkdirs()

        val varsContent = buildString {
            appendLine("# Auto-generated by kinfra config command")
            appendLine("# DO NOT EDIT MANUALLY")
            appendLine()

            hostsConfig.hosts.forEach { (hostName, enabled) ->
                appendLine("enable_$hostName = $enabled")
            }
        }

        varsFile.writeText(varsContent)
    }

    override fun getVarsFilePath(): String {
        return File(varsFilePath).absolutePath
    }
}