#!/bin/bash
##################################################
set -ue
BIN_DIR=$(cd "$(dirname "${BASH_SOURCE:-$0}")"; pwd)
##################################################

chmod +x "$BIN_DIR"/*

git add -A
git commit -m "script" || true
git pull --no-rebase
git push

