#!/bin/bash
##################################################
set -ue
BIN_DIR=$(cd "$(dirname "${BASH_SOURCE:-$0}")"; pwd)
##################################################
git add -A && git commit -m "script" || true && git pull --no-rebase && git push
main() {
  cd "$BIN_DIR/.."
  ./gradlew build
  java -jar build/libs/kinfra-all.jar deploy
}
main
