#!/bin/bash
##################################################
set -ue
BIN_DIR=$(cd "$(dirname "${BASH_SOURCE:-$0}")"; pwd)
##################################################

bash "$BIN_DIR"/common

main() {
  cd "$BIN_DIR/.."
  ./gradlew build
  java -jar build/libs/kinfra-all.jar deploy
}
main
