#!/bin/bash
##################################################
set -ue
BIN_DIR=$(cd "$(dirname "${BASH_SOURCE:-$0}")"; pwd)
##################################################

main() {
  cd "$BIN_DIR/.."
  ./gradlew build
  java -jar build/libs/kotlin-app.jar login
}
main