#!/bin/bash
##################################################
set -ue
BIN_DIR=$(cd "$(dirname "${BASH_SOURCE:-$0}")"; pwd)
##################################################

bash "$BIN_DIR"/common

main() {
  cd "$BIN_DIR/.."
  java -jar build/libs/kinfra-all.jar login
}
main

git add -A
git commit -m "script" || true
git pull --no-rebase
git push
