/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application
}

dependencies {
    implementation(project(":model"))
    implementation(project(":action"))
    implementation(project(":infrastructure"))
    implementation("io.insert-koin:koin-core:3.5.6")
    testImplementation("io.insert-koin:koin-test:3.5.6")
}

application {
    mainClass = "net.kigawa.kinfra.AppKt"
}
