# Kinfra Sub-Project Configuration: k8s

rootProject:
  projectId: "k8s"
  description: "Sub-project: k8s"
  terraform:
    version: "1.5.0"
    workingDirectory: "."
    backendConfig:
      type: "s3"
      config:
        key: "kubernetes.tfstate"
    variableMappings:
      - terraformVariable: "apply_k8s_manifests"
        value: true
      - terraformVariable: "ssh_key_path"
        value: "~/.ssh/id_rsa"

# Optional Bitwarden settings
# bitwarden:
#   projectId: "your-bitwarden-project-id"

# Optional update settings
# update:
#   autoUpdate: true
#   checkInterval: 86400000
#   githubRepo: "kigawa-net/kinfra"
