apiVersion: v1
kind: Pod
metadata:
  name: knot-pod
  namespace: kube-system
  labels:
    k8s-app: knot-pod
spec:
  containers:
    - name: knot-resolver-con
      image: cznic/knot-resolver
      volumeMounts:
        - name: knot-resolver-conf
          mountPath: /etc/knot-resolver
  initContainers:
    - name: knot-con
      image: cznic/knot-dns
      restartPolicy: Always
      volumeMounts:
        - name: knot-config
          mountPath: /etc/knot
        - name: knot-zones
          mountPath: /var/lib/knot/zones
        - name: knot-db
          mountPath: /var/lib/knot
      ports:
        - containerPort: 53
          protocol: UDP
        - containerPort: 53
          protocol: TCP
  volumes:
    - name: knot-resolver-conf
      configMap:
        name: knot-resolver-conf
        items:
          - key: config.yaml
            path: config.yaml
            mode: 0644
    - name: knot-config
      hostPath:
        path: /etc/knot
        type: Directory
    - name: knot-zones
      hostPath:
        path: /var/lib/knot/zones
        type: Directory
    - name: knot-db
      hostPath:
        path: /var/lib/knot
        type: Directory
  restartPolicy: Always
