apiVersion: v1
kind: Service
metadata:
  name: knot-svc
spec:
  selector:
    app: knot-pod
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
    - protocol: TCP
      port: 53
      targetPort: 53
  type: NodePort
  